### ISSUE TITLE
Landing Page Toolbar Selection Issue - CTree and Participate

### ISSUE THREAD

**Issue by begunfx** [F4IF/ctree-demo#104]
When selecting any of the following toolbar options: Overview, Feedback, or Features (which all scroll the screen) then select Participate.  The toolbar will switch the active selection to cTree.  If we are already on cTree or Participate and select either one the toolbar selection executes as expected.

**Comment by begunfx** [comment]
This should be fixed now.  We were missing a cTree section, but had it in the tab list, so that seems to be why when we selected Participate from another tab it would get a bit confused.  (Fixed in develop-landing-page_begunfx branch).

**Comment by CSchmitz81** [comment]
Is there a change required for this?  It sounds like it since you talked about a fix.  If so, we should reopen this until the fix has been merged in.

It's best to have separate pull requests for each issue, but if you rolled changes for multiple issues into one branch just be sure to mention each issue in the pull request.

**Comment by begunfx** [comment]
It should be fixed in my branch.  Okay, no worries, I'll re-open this until we merge the branches.
